language: java
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - cd com.examples.myproject/
   - mvn clean package

notifications:
  email:
    recipients:
      - adityacse2019@gmail.com
      - aditya.singh@bangmetric.com

    on_success: always 
    on_failure: never
